services:
  - type: web
    name: rabble-games-gateway
    env: node
    plan: starter
    nodeVersion: 18.x
    buildCommand: |
      yarn install && 
      yarn build &&
      mkdir -p packages/rabble-proviva/public packages/doritos/public &&
      cp -r packages/rabble-proviva/public packages/rabble-proviva/ &&
      cp -r packages/doritos/public packages/doritos/
    startCommand: yarn start
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
